# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 11:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('considerations', models.TextField()),
                ('date_started', models.DateField(auto_now=True)),
                ('organizational_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('physical_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('functional_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mov_public_knowledge_noq', models.IntegerField(default=0)),
                ('mov_media_noq', models.IntegerField(default=0)),
                ('mov_official_document_noq', models.IntegerField(default=0)),
                ('degree_of_completion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('city_id_completion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stakeholders_completion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hazards_completion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentChoicesMC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentChoicesMC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentChoicesMC4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentCityIDChoicesOtherTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentCityIDQuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('remote_folder', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentCityIDSectionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('spatial_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('organizational_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('physical_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('functional_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mov_public_knowledge_noq', models.IntegerField(default=0)),
                ('mov_media_noq', models.IntegerField(default=0)),
                ('mov_official_document_noq', models.IntegerField(default=0)),
                ('degree_of_completion', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentElementImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentHazardCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentHazardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentHazardConsequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentHazardSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentHazardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_assessment', models.CharField(blank=True, max_length=50, null=True)),
                ('r_a_year', models.CharField(blank=True, max_length=50, null=True)),
                ('contingency_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('c_p_year', models.CharField(blank=True, max_length=50, null=True)),
                ('subtypes', models.CharField(blank=True, max_length=250, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('engagement_from_local_gov', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_to_local_gov', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentStakeholderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('assessment_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentStakeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_released', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesAirTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesCityRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesGasSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMC4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMoVScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesMoVSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesOtherTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesRailTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesRoadTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesSC9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesStakeholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoicesWaterTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityIDQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_short', models.CharField(blank=True, max_length=150, null=True)),
                ('question_long', models.CharField(blank=True, max_length=500, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('choices', models.CharField(blank=True, max_length=50, null=True)),
                ('multi', models.BooleanField(default=False)),
                ('question_type', models.CharField(blank=True, max_length=25, null=True)),
                ('not_applicable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityIDSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, max_length=250, null=True)),
                ('next_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_section', to='crpt201511.CityIDSection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_section', to='crpt201511.CityIDSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityIDSectionConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.CityIDSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('add_type', models.IntegerField(default=0)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentVersion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=800)),
                ('type', models.CharField(max_length=25)),
                ('show_separator', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_short', models.CharField(blank=True, max_length=150, null=True)),
                ('question_long', models.CharField(blank=True, max_length=500, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('choices', models.CharField(blank=True, max_length=50, null=True)),
                ('multi', models.BooleanField(default=False)),
                ('question_type', models.CharField(blank=True, max_length=25, null=True)),
                ('not_applicable', models.BooleanField(default=False)),
                ('has_mov', models.BooleanField(default=False)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('mov_type', models.CharField(blank=True, max_length=10, null=True)),
                ('mov_position', models.IntegerField(default=0)),
                ('add_type', models.IntegerField(default=0)),
                ('show_short_name', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Element')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentVersion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Element')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardSubtypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('hazard_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardSubtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardSubtypeFurtherExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('hazard_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardSubtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('hazard_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoVType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_title', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field2', models.CharField(blank=True, max_length=500, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment')),
                ('field3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.MoVType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('help_text', models.CharField(blank=True, max_length=250, null=True)),
                ('next_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Stakeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StakeholderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('next_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.StakeholderGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StakeholderGroupConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('stakeholder_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.StakeholderGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StakeholderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('help_text', models.CharField(blank=True, max_length=250, null=True)),
                ('next_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.StakeholderType')),
                ('stakeholder_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.StakeholderGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentCityIDQuestion',
            fields=[
                ('cityidquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crpt201511.CityIDQuestion')),
                ('response', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('crpt201511.cityidquestion',),
        ),
        migrations.CreateModel(
            name='AssessmentComponentQuestion',
            fields=[
                ('componentquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crpt201511.ComponentQuestion')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('response', models.CharField(blank=True, max_length=250, null=True)),
                ('choices_length', models.IntegerField(default=0)),
                ('scorable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('crpt201511.componentquestion',),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='stakeholder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.StakeholderType'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Role'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazardsubtype',
            name='hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardType'),
        ),
        migrations.AddField(
            model_name='componentquestion',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Component'),
        ),
        migrations.AddField(
            model_name='componentquestion',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Dimension'),
        ),
        migrations.AddField(
            model_name='componentquestion',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Element'),
        ),
        migrations.AddField(
            model_name='componentquestion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentVersion'),
        ),
        migrations.AddField(
            model_name='component',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Dimension'),
        ),
        migrations.AddField(
            model_name='component',
            name='next_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_element', to='crpt201511.Component'),
        ),
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_element', to='crpt201511.Component'),
        ),
        migrations.AddField(
            model_name='cityidquestion',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Element'),
        ),
        migrations.AddField(
            model_name='cityidquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.CityIDSection'),
        ),
        migrations.AddField(
            model_name='cityidquestion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentVersion'),
        ),
        migrations.AddField(
            model_name='assessmentstakeholdercomment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person'),
        ),
        migrations.AddField(
            model_name='assessmentstakeholder',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Stakeholder'),
        ),
        migrations.AddField(
            model_name='assessmenthazardtype',
            name='hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardsubtype',
            name='a_h_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardsubtype',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmenthazardsubtype',
            name='h_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.HazardSubtype'),
        ),
        migrations.AddField(
            model_name='assessmenthazardconsequence',
            name='a_h_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardconsequence',
            name='a_h_type_consequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ht_consequence', to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardconsequence',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmenthazardcomment',
            name='assessment_hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardcomment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person'),
        ),
        migrations.AddField(
            model_name='assessmenthazardcause',
            name='a_h_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardcause',
            name='a_h_type_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ht_cause', to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmenthazardcause',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentelementimpact',
            name='a_h_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentHazardType'),
        ),
        migrations.AddField(
            model_name='assessmentelementimpact',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentelementimpact',
            name='elem_impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.ElementImpact'),
        ),
        migrations.AddField(
            model_name='assessmentelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Element'),
        ),
        migrations.AddField(
            model_name='assessmentelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_a_element', to='crpt201511.AssessmentElement'),
        ),
        migrations.AddField(
            model_name='assessmentcomponentcomment',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Component'),
        ),
        migrations.AddField(
            model_name='assessmentcomponentcomment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person'),
        ),
        migrations.AddField(
            model_name='assessmentcityidsectioncomment',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.CityIDSection'),
        ),
        migrations.AddField(
            model_name='assessmentcityidsectioncomment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.City'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='focal_point_started',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Person'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentVersion'),
        ),
        migrations.AddField(
            model_name='assessmentcomponentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentcomponentquestion',
            name='assessment_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentElement'),
        ),
        migrations.AddField(
            model_name='assessmentcityidquestionfile',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentCityIDQuestion'),
        ),
        migrations.AddField(
            model_name='assessmentcityidquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crpt201511.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentcityidquestion',
            name='assessment_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crpt201511.AssessmentElement'),
        ),
    ]
