# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpt201511', '0002_auto_20160525_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcomponentquestion',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
