# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpt201511', '0004_auto_20160526_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='city_id_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='degree_of_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='functional_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='hazards_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='organizational_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='physical_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='stakeholders_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentcomponentquestion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentcomponentquestion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentelement',
            name='degree_of_completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentelement',
            name='functional_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentelement',
            name='organizational_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentelement',
            name='physical_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='assessmentelement',
            name='spatial_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
